#!/bin/bash
# =============================================================================
# CraftAI - Docker Entrypoint Script
# Handles runtime environment variable injection for Vite apps
# =============================================================================

set -e

echo "🚀 Starting CraftAI application..."

# Define the directory where built files are located
HTML_DIR="/usr/share/nginx/html"

echo "📦 Creating runtime configuration file..."

# Validate required environment variables
echo "🔍 Validating environment variables..."
MISSING_VARS=0

if [ -z "${VITE_BOLNA_API_KEY}" ]; then
    echo "   ❌ ERROR: VITE_BOLNA_API_KEY is not set"
    MISSING_VARS=1
fi

if [ -z "${VITE_BOLNA_AGENT_PRIYA}" ]; then
    echo "   ❌ ERROR: VITE_BOLNA_AGENT_PRIYA is not set"
    MISSING_VARS=1
fi

if [ -z "${VITE_BOLNA_AGENT_TRIPTI}" ]; then
    echo "   ❌ ERROR: VITE_BOLNA_AGENT_TRIPTI is not set"
    MISSING_VARS=1
fi

if [ -z "${VITE_BOLNA_AGENT_ARUN}" ]; then
    echo "   ❌ ERROR: VITE_BOLNA_AGENT_ARUN is not set"
    MISSING_VARS=1
fi

if [ $MISSING_VARS -eq 1 ]; then
    echo ""
    echo "💡 Solution: Pass environment variables to Docker:"
    echo ""
    echo "   Using docker-compose:"
    echo "   docker-compose --env-file .env up craftai-prod"
    echo ""
    echo "   Using docker run:"
    echo "   docker run -p 8080:80 \\"
    echo "     -e VITE_BOLNA_API_KEY=your_key \\"
    echo "     -e VITE_BOLNA_AGENT_PRIYA=priya_id \\"
    echo "     -e VITE_BOLNA_AGENT_TRIPTI=tripti_id \\"
    echo "     -e VITE_BOLNA_AGENT_ARUN=arun_id \\"
    echo "     craftai:latest"
    echo ""
    exit 1
fi

echo "   ✅ All environment variables are set"
echo ""

# Create a runtime config.js file with environment variables
cat > "${HTML_DIR}/config.js" <<EOF
// Runtime Configuration - Generated by Docker
window.__ENV__ = {
  VITE_BOLNA_API_KEY: "${VITE_BOLNA_API_KEY}",
  VITE_BOLNA_AGENT_PRIYA: "${VITE_BOLNA_AGENT_PRIYA}",
  VITE_BOLNA_AGENT_TRIPTI: "${VITE_BOLNA_AGENT_TRIPTI}",
  VITE_BOLNA_AGENT_ARUN: "${VITE_BOLNA_AGENT_ARUN}",
};
EOF

if [ -f "${HTML_DIR}/config.js" ]; then
    echo "   ✅ Runtime config.js created successfully"
    echo "   ✓ VITE_BOLNA_API_KEY: ${VITE_BOLNA_API_KEY:0:15}... (masked)"
    echo "   ✓ VITE_BOLNA_AGENT_PRIYA: ${VITE_BOLNA_AGENT_PRIYA}"
    echo "   ✓ VITE_BOLNA_AGENT_TRIPTI: ${VITE_BOLNA_AGENT_TRIPTI}"
    echo "   ✓ VITE_BOLNA_AGENT_ARUN: ${VITE_BOLNA_AGENT_ARUN}"
else
    echo "   ❌ Failed to create config.js"
    exit 1
fi

# Print configuration summary
echo ""
echo "📋 Configuration Summary:"
echo "   - API Endpoint: Configured"
echo "   - Agent Count: 3 agents"
echo "   - Runtime config: /config.js"
echo ""

# Execute the main command (nginx)
echo "🌐 Starting Nginx server..."
exec "$@"
